### ISSUE TITLE
TODO Stuff

### ISSUE THREAD

**Issue by InfiniZest** [Infinite-Zest001/notificationface#1]
- [x] Refator to Java
   - [x] Refactored MyWatchFace
   - [x] Refactored NotificationListener
- [ ] Changed watch face font to Google-sans
- [ ] Medium size date (dates on most watchfaces are too small).
- [ ] Watch battery indicator
- [ ] Added a date below time 
- [ ] Added a settings interface for the end-user
    - [ ] Added a toggle to set 12/24 hr format
    - [ ] Added a toggle to remove date
    - [ ] Added a weather toggle
    - [ ] Added a background selector (Choose a wallpaper you want to add from your phone, crop, and 
      send. The watch will refresh showing the new wallpaper.
- [ ] Added an animation that slides the face presets upwards to show notification icons

**Comment by Infinite-Zest001** [comment]
### End goal:
![notificationfacemockup](https://user-images.githubusercontent.com/17032841/41571876-3f85da74-7343-11e8-826a-c86743afd910.png)

**Comment by Infinite-Zest001** [comment]
The battery line is customizable

**Comment by InfiniZest** [comment]
![watchfaceconcept](https://user-images.githubusercontent.com/17032841/43106709-d7bf9328-8ea7-11e8-809b-bf86c3849c73.png)
